### ISSUE TITLE
Décompte lors du nommage ou lancement sysprep trop court

### ISSUE THREAD

**Issue by mollef** [SambaEdu/sambaedu-client-windows#13]
Lors de l'intégration manuelle, deux poses s'effectuent
* Lors du nommage 
* Lors de la proposition de lancement de sysprep

Ces deux pauses durent 10s et sont très / trop courtes. Je propose donc :
* 20s pour le lancement de sysprep car en général on ne le lance pas
* 30s voire 40s pour le nommage

**Comment by mbansse** [comment]
J'ai du intégrer 120 postes hier, et effectivement, le décompte est bien trop court, surtout que la fenêtre n'est pas active lorsqu'elle apparaît et qu'il faut attendre déjà plus d'une minute avant que la partie nom soit indiquée. il faut donc recliquer sur la fenêtre et taper "n".
Une minute ne me parait pas excessive si on doit intégrer des postes simultanément. Mon collègue était tellement stressé par cela qu'il a souvent raté le coche au début créant des doublons d'annuaire, jusqu'à modification de la valeur "10" dans le fichier n°1.

**Comment by denis-b** [comment]
La bonne méthode est de relever les adresses Mac de faire un fichier de
réservations,  et ensuite cetautomatix

**Comment by mollef** [comment]
Plus d'actualité en mode AD
