### ISSUE TITLE
Permettre l'intégration sans sysprep

### ISSUE THREAD

**Issue by denis-b** [SambaEdu/sambaedu-client-windows#2]
Imposer un sysprep avant l'intégration au domaine sambaedu permet de garantir que le poste est en bon état, et donc que par la suite sa maintenance sera prévisible. Or dans de nombreux cas (la plupart ?), il n'est pas possible de lancer un sysprep sur un poste ayant déjà servi. 

Il faudrait donc, en cas d'échec du sysprep à l'intégration, proposer de faire malgré tout celle-ci mais en avertissant bien l'utilisateur que son poste sera dans une configuration non supportée.

**Comment by denis-b** [comment]
J'ai une version qui fonctionne sans sysprep, mais le problème qui se pose c'est la detection de l'os qui est problématique.  ll faudrait revoir https://github.com/SambaEdu/se3-domain/commit/2987e720e9cab18d30162ab0666fbd2ff0af83d8#diff-f99ff4b90f7dc5afc6156c4f6bdaae81 car je ne suis pas du tout sûr que cela fonctionne...

**Comment by SambaEdu** [comment]
La dernière version est celle-ci : 
https://github.com/SambaEdu/se3-domain/commit/ba9c346b86ad5631115cba0123989381b31f16d8

L'idée soumise ici est effectivement à creuser car  le test actuel ne m'inspire pas confiance.....
https://github.com/SambaEdu/se3master/issues/15

**Comment by denis-b** [comment]
Attention, la version 0.6 est expérimentale. En pariculier aucun test en w7 !

**Comment by SambaEdu** [comment]
0.6 dispo en dépots testing et XP

**Comment by swirly** [comment]
Denis, plus que l'idée d'avoir une version qui fonctionne même si le sysprep échoue (cas classique avec un antivirus un peu attentif), avoir le choix de fonctionner avec ou sans sysprep me semblerait encore mieux (soit via une option, soit via deux exécutables différents)

**Comment by SambaEdu** [comment]
Suite discussion du jour 

- Le script d'intégration manuel doit par défaut faire l’intégration sans sysprep --> 
  - Ajout d'une option /sysprep pour forcer un sysprep si besoin est par l'opérateur
- En mode clonage les postes w7 doivent utiliser l'ancienne méthode d'intégration ou  la nouvelle sans sysprep. Seul w10 doit lancer un sysprep et uniquement lors d'un clonage.

**Comment by denis-b** [comment]
fait.
