### ISSUE TITLE
echec net use dans ipxe/Win10/install.bat

### ISSUE THREAD

**Issue by jlcf** [SambaEdu/sambaedu-client-windows#8]
J'ai été plusieurs fois confronté à l'échec du net use dans install.bat.

j'ai modifié install.bat ainsi 👍 j’ai été plusieurs fois confontré a un échec lors de l’exécution du net use dans le ipxe/install.bat

j’ai modifié le install.bat ainsi :

wpeinit.exe
call se3w10-vars.cmd
REM ****** Renew IP
IPCONFIG /RENEW
PING 127.0.0.1
IPCONFIG /RENEW
PING 127.0.0.1
IPCONFIG /RENEW
PING 127.0.0.1
net use z: \\%SE3IP%\install /user:adminse3 %XPPASS%
z:\os\Win10\setup.exe /unattend:z:\os\netinst\unattend.xml

voir : https://social.technet.microsoft.com/Forums/windows/en-US/c999b70c-b69a-4861-acaa-5e2656e64f3a/net-use-doesnt-work-with-winpe?forum=itprovistadeployment

**Comment by denis-b** [comment]
Changement appliqué.
