### ISSUE TITLE
amélioration d'utilisation du menu pxe

### ISSUE THREAD

**Issue by msuquet** [SambaEdu/sambaedu-client-windows#9]
dans le fichier /tftpboot/pxelinux.cfg/install.menu
modifier les lignes de label pour avoir ceci :
MENU LABEL Installation ^Windows

ainsi que les 2 autres lignes de label :
MENU LABEL Installation ^Debian ← enlever aussi la mention Jessie
MENU LABEL Installation ^Ubuntu

Ainsi, on pourra utiliser les touches W, D et U pour aller directement aux lignes correspondantes.

**Comment by mollef** [comment]
A migrer en IPXE
